# Your personal GitHub token
github_token: 4d37ae317d360bc19a9fb02ad0bfc41f541eb693
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Asia/Tashkent

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: shy

# Virtual machine IP
ip: 192.168.55.63

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 512
