version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: docker/frontend.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    links:
      - php
  backend:
    build:
      context: ./
      dockerfile: docker/backend.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8081:443"
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: docker/php.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_USER=fatam"
      - "MYSQL_DATABASE=fatam"
      - "MYSQL_PASSWORD=123"
      - "MYSQL_ROOT_PASSWORD=123"
    ports:
      - "3306:3306"
  redis:
    image: redis:3.0
    ports:
      - "63791:6379"
  node:
    build:
      context: ./
      dockerfile: docker/node.docker
    volumes:
      - ./:/var/www
    tty: true
